language: python

before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below

after_success:
    - coveralls